<?php
namespace ResourceCatalog\Model\TemplateModel;

class ResourceCatalogSjyjModel
{
    const TEMPLATE = array(
        'JYJGXX' => array(
            array('englishName'=>'name', 'name'=>'学校/机构名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'学校代码/统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'department', 'name'=>'上级管理行政部门', 'validationRules'=>array()),
            array('englishName'=>'schoolType', 'name'=>'办学类型', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'JSZGXX' => array(
            array('englishName'=>'name', 'name'=>'姓名', 'validationRules'=>array()),
            array('englishName'=>'gender', 'name'=>'性别', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'身份证号', 'validationRules'=>array()),
            array('englishName'=>'certificateName', 'name'=>'证书名称', 'validationRules'=>array()),
            array('englishName'=>'certificateNumber', 'name'=>'证书编号', 'validationRules'=>array()),
            array('englishName'=>'qualificationType', 'name'=>'资格种类', 'validationRules'=>array()),
            array('englishName'=>'subject', 'name'=>'任教学科', 'validationRules'=>array()),
            array('englishName'=>'issuingDate', 'name'=>'发证日期', 'validationRules'=>array()),
            array('englishName'=>'issuingUnit', 'name'=>'发证机构', 'validationRules'=>array()),
            array('englishName'=>'validityDateStart', 'name'=>'有效起始日期', 'validationRules'=>array()),
            array('englishName'=>'validityDateEnd', 'name'=>'有效到期日期', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'SJYXXS' => array(
            array('englishName'=>'name', 'name'=>'姓名', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'身份证号', 'validationRules'=>array()),
            array('englishName'=>'honoraryTitle', 'name'=>'荣誉称号', 'validationRules'=>array()),
            array('englishName'=>'certificateNumber', 'name'=>'文号/证书编号', 'validationRules'=>array()),
            array('englishName'=>'honorContent', 'name'=>'荣誉事项内容', 'validationRules'=>array()),
            array('englishName'=>'evaluationDate', 'name'=>'评定/认定日期', 'validationRules'=>array()),
            array('englishName'=>'evaluationUnit', 'name'=>'评定/认定单位', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'JYJGXINXI' => array(
            array('englishName'=>'name', 'name'=>'学校/机构名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码/学校代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'身份证号', 'validationRules'=>array()),
            array('englishName'=>'certificateNumber', 'name'=>'证书编号', 'validationRules'=>array()),
            array('englishName'=>'content', 'name'=>'办学内容', 'validationRules'=>array()),
            array('englishName'=>'licensingDate', 'name'=>'许可日期', 'validationRules'=>array()),
            array('englishName'=>'licensingUnit', 'name'=>'许可机构', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'GRRYXXJYJ' => array(
            array('englishName'=>'name', 'name'=>'姓名', 'validationRules'=>array()),
            array('englishName'=>'gender', 'name'=>'性别', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'身份证号码', 'validationRules'=>array()),
            array('englishName'=>'honoraryTitle', 'name'=>'荣誉称号/获奖名称', 'validationRules'=>array()),
            array('englishName'=>'grantingUnit', 'name'=>'授予（评定）单位', 'validationRules'=>array()),
            array('englishName'=>'grantingYear', 'name'=>'授予（评定）年份', 'validationRules'=>array()),
            array('englishName'=>'commendationCode', 'name'=>'表彰文号', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
    );
}