<?php
namespace ResourceCatalog\Model\TemplateModel;

class ResourceCatalogSdfswjModel
{
    const TEMPLATE = array(
        'QYDSXZCFXX' => array(
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'社会信用代码（纳税人识别号）', 'validationRules'=>array()),
            array('englishName'=>'name', 'name'=>'纳税人名称', 'validationRules'=>array()),
            array('englishName'=>'caseNumber', 'name'=>'案件编号', 'validationRules'=>array()),
            array('englishName'=>'caseName', 'name'=>'案件名称', 'validationRules'=>array()),
            array('englishName'=>'caseTaxAuthority', 'name'=>'案件所在税务机关', 'validationRules'=>array()),
            array('englishName'=>'paymentLimitTerm', 'name'=>'限缴期限', 'validationRules'=>array()),
            array('englishName'=>'finePaymentLimitDay', 'name'=>'罚款限缴天数', 'validationRules'=>array()),
            array('englishName'=>'payableFine', 'name'=>'应缴罚款金额', 'validationRules'=>array()),
            array('englishName'=>'paidinFine', 'name'=>'实缴罚款金额', 'validationRules'=>array()),
            array('englishName'=>'reconsiderationOrgan', 'name'=>'复议机关名称', 'validationRules'=>array()),
            array('englishName'=>'clericalCharacterTrack', 'name'=>'文书字轨', 'validationRules'=>array()),
            array('englishName'=>'papermakingDate', 'name'=>'文书制作日期', 'validationRules'=>array()),
            array('englishName'=>'deliveryDate', 'name'=>'文书送达日期', 'validationRules'=>array()),
            array('englishName'=>'industry', 'name'=>'行业', 'validationRules'=>array()),
            array('englishName'=>'registrationType', 'name'=>'登记注册类型', 'validationRules'=>array()),
            array('englishName'=>'streetTown', 'name'=>'街道乡镇', 'validationRules'=>array()),
            array('englishName'=>'taxAdministrator', 'name'=>'税收管理员', 'validationRules'=>array()),
            array('englishName'=>'competentTaxAuthorities', 'name'=>'主管税务机关', 'validationRules'=>array()),
            array('englishName'=>'documentNumber', 'name'=>'批准设立证明或文件号', 'validationRules'=>array()),
            array('englishName'=>'certificate', 'name'=>'证照名称', 'validationRules'=>array()),
            array('englishName'=>'certificateNumber', 'name'=>'证照号码', 'validationRules'=>array()),
            array('englishName'=>'organizationCode', 'name'=>'组织机构代码', 'validationRules'=>array()),
            array('englishName'=>'openingDate', 'name'=>'开业(设立)日期', 'validationRules'=>array()),
            array('englishName'=>'certificatesHandling', 'name'=>'办证方式', 'validationRules'=>array()),
            array('englishName'=>'regularQuotaSign', 'name'=>'定期定额标志', 'validationRules'=>array()),
            array('englishName'=>'accountingMmethod', 'name'=>'核算方式', 'validationRules'=>array()),
            array('englishName'=>'industryDetail', 'name'=>'国标行业/行业明细', 'validationRules'=>array()),
            array('englishName'=>'accountingSystem', 'name'=>'适用会计制度', 'validationRules'=>array()),
            array('englishName'=>'financialOfficer', 'name'=>'财务负责人', 'validationRules'=>array()),
            array('englishName'=>'taxMan', 'name'=>'办税人', 'validationRules'=>array()),
            array('englishName'=>'registeredCapital', 'name'=>'注册资本', 'validationRules'=>array()),
            array('englishName'=>'naturalPersonInvestmentRatio', 'name'=>'自然人投资比例(%)', 'validationRules'=>array()),
            array('englishName'=>'foreignInvestmentRatio', 'name'=>'外资投资比例(%)', 'validationRules'=>array()),
            array('englishName'=>'stateInvestmentRatio', 'name'=>'国有投资比例(%)', 'validationRules'=>array()),
            array('englishName'=>'taxpayersTownships', 'name'=>'纳税人所处街乡', 'validationRules'=>array()),
            array('englishName'=>'affiliation', 'name'=>'隶属关系', 'validationRules'=>array()),
            array('englishName'=>'householdManagementType', 'name'=>'国地管户类型', 'validationRules'=>array()),
            array('englishName'=>'totalInvestment', 'name'=>'投资总额', 'validationRules'=>array()),
            array('englishName'=>'tempTaxRgstrtionVldtyPeriod', 'name'=>'临时税务登记有效期起', 'validationRules'=>array()),
            array('englishName'=>'tempTaxRgstrtionVldtyTerm', 'name'=>'临时税务登记有效期止', 'validationRules'=>array()),
            array('englishName'=>'partnersNumber', 'name'=>'合伙人数', 'validationRules'=>array()),
            array('englishName'=>'partnersInfo', 'name'=>'合伙信息', 'validationRules'=>array()),
            array('englishName'=>'withholdingInfo', 'name'=>'代扣代缴信息', 'validationRules'=>array()),
            array('englishName'=>'tempTaxAdministrator', 'name'=>'税收管理员', 'validationRules'=>array()),
            array('englishName'=>'tempCompetentTaxAuthorities', 'name'=>'主管税务机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
    );
}