<?php
namespace ResourceCatalog\Model\TemplateModel;

class ResourceCatalogSschzljggljModel
{
    const TEMPLATE = array(
        'QYJBXX' => array(
            array('englishName'=>'name', 'name'=>'企业名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法定代表人', 'validationRules'=>array()),
            array('englishName'=>'residence', 'name'=>'住所（经营场所）', 'validationRules'=>array()),
            array('englishName'=>'enterpriseTypeCode', 'name'=>'企业类型代码', 'validationRules'=>array()),
            array('englishName'=>'registeredCapital', 'name'=>'注册资本（金）', 'validationRules'=>array()),
            array('englishName'=>'currency', 'name'=>'币种（限外资企业）', 'validationRules'=>array()),
            array('englishName'=>'establishmentDate', 'name'=>'成立日期', 'validationRules'=>array()),
            array('englishName'=>'approvalDate', 'name'=>'核准日期', 'validationRules'=>array()),
            array('englishName'=>'limitBusinessPeriod', 'name'=>'经营期限止', 'validationRules'=>array()),
            array('englishName'=>'businessScope', 'name'=>'经营范围', 'validationRules'=>array()),
            array('englishName'=>'registratioAuthority', 'name'=>'登记机关', 'validationRules'=>array()),
            array('englishName'=>'registrationState', 'name'=>'登记状态', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'GTGSHXX' => array(
            array('englishName'=>'name', 'name'=>'个体名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'businessScope', 'name'=>'经营范围', 'validationRules'=>array()),
            array('englishName'=>'registrationState', 'name'=>'登记状态', 'validationRules'=>array()),
            array('englishName'=>'nameOfOperator', 'name'=>'经营者姓名', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'经营者身份证号码', 'validationRules'=>array()),
            array('englishName'=>'operatingAddress', 'name'=>'经营地址行政区域', 'validationRules'=>array()),
            array('englishName'=>'placeOfBusiness', 'name'=>'经营场所', 'validationRules'=>array()),
            array('englishName'=>'industryCategory', 'name'=>'行业门类', 'validationRules'=>array()),
            array('englishName'=>'industryCode', 'name'=>'行业代码', 'validationRules'=>array()),
            array('englishName'=>'amountOfFunds', 'name'=>'资金数额', 'validationRules'=>array()),
            array('englishName'=>'termOfOperationStart', 'name'=>'经营期限起', 'validationRules'=>array()),
            array('englishName'=>'termOfOperationEnd', 'name'=>'经营期限至', 'validationRules'=>array()),
            array('englishName'=>'registratioAuthority', 'name'=>'登记机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'CMQYSBXX' => array(
            array('englishName'=>'name', 'name'=>'企业名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'trademarkRegistrant', 'name'=>'商标注册人', 'validationRules'=>array()),
            array('englishName'=>'trademarkName', 'name'=>'商标名称', 'validationRules'=>array()),
            array('englishName'=>'certifiedCategory', 'name'=>'认定类别', 'validationRules'=>array()),
            array('englishName'=>'certifiedCommodity', 'name'=>'认定商品', 'validationRules'=>array()),
            array('englishName'=>'certifiedYear', 'name'=>'认定年份', 'validationRules'=>array()),
            array('englishName'=>'certifiedDepartment', 'name'=>'认定部门', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'YPLSQYXX' => array(
            array('englishName'=>'name', 'name'=>'企业名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'enterpriseLeader', 'name'=>'企业负责人', 'validationRules'=>array()),
            array('englishName'=>'qualityLeader', 'name'=>'质量负责人', 'validationRules'=>array()),
            array('englishName'=>'address', 'name'=>'注册地址', 'validationRules'=>array()),
            array('englishName'=>'businessLicenseNumber', 'name'=>'经营许可证编号', 'validationRules'=>array()),
            array('englishName'=>'businessScope', 'name'=>'经营范围', 'validationRules'=>array()),
            array('englishName'=>'operationMode', 'name'=>'经营方式', 'validationRules'=>array()),
            array('englishName'=>'issuingDate', 'name'=>'发证日期', 'validationRules'=>array()),
            array('englishName'=>'validTill', 'name'=>'有效期至', 'validationRules'=>array()),
            array('englishName'=>'issuingUnit', 'name'=>'发证机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'JGRYXX' => array(
            array('englishName'=>'name', 'name'=>'机构名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'honorName', 'name'=>'获奖或荣誉名称', 'validationRules'=>array()),
            array('englishName'=>'grantingYear', 'name'=>'获奖年度', 'validationRules'=>array()),
            array('englishName'=>'validityTerm', 'name'=>'有效期', 'validationRules'=>array()),
            array('englishName'=>'evaluationInstitution', 'name'=>'评定机构', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'SXQYHMD' => array(
            array('englishName'=>'name', 'name'=>'企业名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'punishmentBasis', 'name'=>'处罚依据', 'validationRules'=>array()),
            array('englishName'=>'punishmentDecision', 'name'=>'行政处罚决定', 'validationRules'=>array()),
            array('englishName'=>'punishmentDate', 'name'=>'处罚日期', 'validationRules'=>array()),
            array('englishName'=>'punishmentOrgan', 'name'=>'处罚机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'SPYPTSJBJLGR' => array(
            array('englishName'=>'name', 'name'=>'姓名', 'validationRules'=>array()),
            array('englishName'=>'gender', 'name'=>'性别', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'身份证号', 'validationRules'=>array()),
            array('englishName'=>'certificateNumber', 'name'=>'证书编号', 'validationRules'=>array()),
            array('englishName'=>'rewardContent', 'name'=>'奖励内容', 'validationRules'=>array()),
            array('englishName'=>'rewardDate', 'name'=>'奖励日期', 'validationRules'=>array()),
            array('englishName'=>'rewardUnit', 'name'=>'奖励机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'SPYPTSJBJLDW' => array(
            array('englishName'=>'name', 'name'=>'企业名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'certificateNumber', 'name'=>'证书编号', 'validationRules'=>array()),
            array('englishName'=>'rewardContent', 'name'=>'奖励内容', 'validationRules'=>array()),
            array('englishName'=>'rewardDate', 'name'=>'奖励日期', 'validationRules'=>array()),
            array('englishName'=>'rewardUnit', 'name'=>'奖励机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'JXMPCPXX' => array(
            array('englishName'=>'name', 'name'=>'企业名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'productName', 'name'=>'名牌产品名称', 'validationRules'=>array()),
            array('englishName'=>'registeredTrademark', 'name'=>'注册商标', 'validationRules'=>array()),
            array('englishName'=>'businessScope', 'name'=>'经营范围', 'validationRules'=>array()),
            array('englishName'=>'issuingDate', 'name'=>'发证日期', 'validationRules'=>array()),
            array('englishName'=>'validTill', 'name'=>'有效期至', 'validationRules'=>array()),
            array('englishName'=>'issuingUnit', 'name'=>'发证机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'QYYCMLXX' => array(
            array('englishName'=>'name', 'name'=>'企业名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'dateOfInclusion', 'name'=>'列入日期', 'validationRules'=>array()),
            array('englishName'=>'reasonsOfInclusion', 'name'=>'列入原因', 'validationRules'=>array()),
            array('englishName'=>'penaltyAgency', 'name'=>'做出处罚机关', 'validationRules'=>array()),
            array('englishName'=>'dateOfRemoval', 'name'=>'移出日期', 'validationRules'=>array()),
            array('englishName'=>'reasonsOfRemoval', 'name'=>'移出原因', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
    );
}