<?php
namespace ResourceCatalog\Model\TemplateModel;

class ResourceCatalogSzjrmfyModel
{
    const TEMPLATE = array(
        'XSPJXX' => array(
            array('englishName'=>'name', 'name'=>'判决人名称', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'判决人身份证号', 'validationRules'=>array(),'outputRules'=>array('mack'),'inputRules'=>array()),
            array('englishName'=>'verdict', 'name'=>'判决机关', 'validationRules'=>array()),
            array('englishName'=>'legalDocumentsEffective', 'name'=>'生效法律文书编号', 'validationRules'=>array()),
            array('englishName'=>'caseType', 'name'=>'案件类型', 'validationRules'=>array()),
            array('englishName'=>'litigationStatus', 'name'=>'诉讼地位', 'validationRules'=>array()),
            array('englishName'=>'filingDate', 'name'=>'立案日期', 'validationRules'=>array()),
            array('englishName'=>'closeDate', 'name'=>'结案日期', 'validationRules'=>array()),
            array('englishName'=>'verdictMainContent', 'name'=>'判决主要内容', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'SXBZXJGXX' => array(
            array('englishName'=>'caseNumber', 'name'=>'案号', 'validationRules'=>array()),
            array('englishName'=>'name', 'name'=>'失信被执行人姓名或名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'身份证号或统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'executionCourt', 'name'=>'执行法院', 'validationRules'=>array()),
            array('englishName'=>'domainName', 'name'=>'地域名', 'validationRules'=>array()),
            array('englishName'=>'executionBasis', 'name'=>'执行依据文号', 'validationRules'=>array()),
            array('englishName'=>'executionBasedUnit', 'name'=>'做出执行依据单位', 'validationRules'=>array()),
            array('englishName'=>'obligationDeterminedLaw', 'name'=>'法律生效文书确定的义务', 'validationRules'=>array()),
            array('englishName'=>'executorPerformance', 'name'=>'被执行人履行情况', 'validationRules'=>array()),
            array('englishName'=>'discreditExecutor', 'name'=>'失信被执行人具体情况', 'validationRules'=>array()),
            array('englishName'=>'releaseTime', 'name'=>'发布时间', 'validationRules'=>array()),
            array('englishName'=>'filingTime', 'name'=>'立案时间', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'企业法人姓名', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'SXBZXRMD' => array(
            array('englishName'=>'name', 'name'=>'失信被执行人姓名', 'validationRules'=>array()),
            array('englishName'=>'age', 'name'=>'年龄', 'validationRules'=>array()),
            array('englishName'=>'gender', 'name'=>'性别', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'身份证号', 'validationRules'=>array(),'outputRules'=>array('mack'),'inputRules'=>array()),
            array('englishName'=>'executionCourt', 'name'=>'执行法院', 'validationRules'=>array()),
            array('englishName'=>'province', 'name'=>'省份', 'validationRules'=>array()),
            array('englishName'=>'executionBasis', 'name'=>'执行依据文号', 'validationRules'=>array()),
            array('englishName'=>'filingTime', 'name'=>'立案时间', 'validationRules'=>array()),
            array('englishName'=>'caseNumber', 'name'=>'案号', 'validationRules'=>array()),
            array('englishName'=>'executionBasedUnit', 'name'=>'做出执行依据单位', 'validationRules'=>array()),
            array('englishName'=>'obligationDeterminedLaw', 'name'=>'法律生效文书确定的义务', 'validationRules'=>array()),
            array('englishName'=>'executorPerformance', 'name'=>'被执行人的履行情况', 'validationRules'=>array()),
            array('englishName'=>'discreditExecutor', 'name'=>'失信被执行人行为具体情形', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
    );
}