<?php
namespace ResourceCatalog\Model\TemplateModel;

class ResourceCatalogSlyfzwyhModel
{
    const TEMPLATE = array(
        'LYQXPDXX' => array(
            array('englishName'=>'name', 'name'=>'县级名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'areaNumber', 'name'=>'区域编号', 'validationRules'=>array()),
            array('englishName'=>'evaluationRating', 'name'=>'评定等级', 'validationRules'=>array()),
            array('englishName'=>'evaluationTime', 'name'=>'评定时间', 'validationRules'=>array()),
            array('englishName'=>'evaluationInstitution', 'name'=>'评定机构', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'XJFDPDXX' => array(
            array('englishName'=>'name', 'name'=>'饭店名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'address', 'name'=>'地址', 'validationRules'=>array()),
            array('englishName'=>'evaluationRating', 'name'=>'评定等级', 'validationRules'=>array()),
            array('englishName'=>'evaluationYear', 'name'=>'评定年度', 'validationRules'=>array()),
            array('englishName'=>'area', 'name'=>'所属区域', 'validationRules'=>array()),
            array('englishName'=>'certificateNumber', 'name'=>'标牌（证书）编号', 'validationRules'=>array()),
            array('englishName'=>'evaluationInstitution', 'name'=>'评定机构', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'DYZGXX' => array(
            array('englishName'=>'name', 'name'=>'姓名', 'validationRules'=>array()),
            array('englishName'=>'gender', 'name'=>'性别', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'身份证号码', 'validationRules'=>array()),
            array('englishName'=>'degree', 'name'=>'学历', 'validationRules'=>array()),
            array('englishName'=>'guideID', 'name'=>'导游证号', 'validationRules'=>array()),
            array('englishName'=>'qualificationNumber', 'name'=>'资格证书号', 'validationRules'=>array()),
            array('englishName'=>'qualificationGrade', 'name'=>'资格等级', 'validationRules'=>array()),
            array('englishName'=>'language', 'name'=>'语种', 'validationRules'=>array()),
            array('englishName'=>'institution', 'name'=>'所在机构', 'validationRules'=>array()),
            array('englishName'=>'approvalDate', 'name'=>'审批日期', 'validationRules'=>array()),
            array('englishName'=>'issuingOrgan', 'name'=>'核发机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'LXSDJXX' => array(
            array('englishName'=>'name', 'name'=>'旅行社名称', 'validationRules'=>array()),
            array('englishName'=>'unifiedSocialCreditCode', 'name'=>'统一社会信用代码', 'validationRules'=>array()),
            array('englishName'=>'address', 'name'=>'旅行社地址', 'validationRules'=>array()),
            array('englishName'=>'principal', 'name'=>'法人代表', 'validationRules'=>array()),
            array('englishName'=>'businessScope', 'name'=>'经营许可范围', 'validationRules'=>array()),
            array('englishName'=>'issuingDate', 'name'=>'核发日期', 'validationRules'=>array()),
            array('englishName'=>'issuingOrgan', 'name'=>'核发机关', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
        'GRRYXXLFW' => array(
            array('englishName'=>'name', 'name'=>'姓名', 'validationRules'=>array()),
            array('englishName'=>'gender', 'name'=>'性别', 'validationRules'=>array()),
            array('englishName'=>'cardID', 'name'=>'身份证号码', 'validationRules'=>array()),
            array('englishName'=>'honoraryTitle', 'name'=>'荣誉称号/获奖名称', 'validationRules'=>array()),
            array('englishName'=>'grantingUnit', 'name'=>'授予（评定）单位', 'validationRules'=>array()),
            array('englishName'=>'grantingYear', 'name'=>'授予（评定）年份', 'validationRules'=>array()),
            array('englishName'=>'commendationCode', 'name'=>'表彰文号', 'validationRules'=>array()),
            array('englishName'=>'subjectCategory', 'name'=>'主体类别', 'validationRules'=>array()),
            array('englishName'=>'infoCategory', 'name'=>'信息类别', 'validationRules'=>array()),
            array('englishName'=>'dimension', 'name'=>'数据共享范围', 'validationRules'=>array()),
            array('englishName'=>'expirationDate', 'name'=>'有效期限', 'validationRules'=>array()),
            array('englishName'=>'exchangeFrequency', 'name'=>'交换频率', 'validationRules'=>array()),
        ),
    );
}