<?php
namespace ResourceCatalog\Model;

interface IResourceCatalogTypeEnName
{
    const TYPE_ENNAME = array(
        IResourceCatalog::TYPE['NULL'] => 0,
        IResourceCatalog::TYPE['JGJCDXZJL'] => 'jgjcdxzjl',
        IResourceCatalog::TYPE['YXQNZYZ'] => 'yxqnzyz',
        IResourceCatalog::TYPE['HRBXX'] => 'hrbxx',
        IResourceCatalog::TYPE['JKQYPJAJYSMD'] => 'jkqypjajysmd',
        IResourceCatalog::TYPE['QXTCHJBHJDXX'] => 'qxtchjbhjdxx',
        IResourceCatalog::TYPE['XSPJXX'] => 'xspjxx',
        IResourceCatalog::TYPE['JYZCXXX'] => 'jyzcxxx',
        IResourceCatalog::TYPE['YSCRJZJJJZGRDXX'] => 'yscrjzjjjzgrdxx',
        IResourceCatalog::TYPE['ZFCGDLJGXX'] => 'zfcgdljgxx',
        IResourceCatalog::TYPE['SJQYJSZXRDXX'] => 'sjqyjszxrdxx',
        IResourceCatalog::TYPE['QYRYXX'] => 'qyryxx',
        IResourceCatalog::TYPE['JYJGXX'] => 'jyjgxx',
        IResourceCatalog::TYPE['SFJDJGCYRYZGXX'] => 'sfjdjgcyryzgxx',
        IResourceCatalog::TYPE['ZYJNZSXX'] => 'zyjnzsxx',
        IResourceCatalog::TYPE['ZLJCQYXX'] => 'zljcqyxx',
        IResourceCatalog::TYPE['PGJGXX'] => 'pgjgxx',
        IResourceCatalog::TYPE['GRYH'] => 'gryh',
        IResourceCatalog::TYPE['SLGCZBXX'] => 'slgczbxx',
        IResourceCatalog::TYPE['QYYH'] => 'qyyh',
        IResourceCatalog::TYPE['QSLHXJJTJL'] => 'qslhxjjtjl',
        IResourceCatalog::TYPE['SLYSXKZXX'] => 'slysxkzxx',
        IResourceCatalog::TYPE['LYQXPDXX'] => 'lyqxpdxx',
        IResourceCatalog::TYPE['SPFYSXK'] => 'spfysxk',
        IResourceCatalog::TYPE['CPTGLSZXCPRZMD'] => 'cptglszxcprzmd',
        IResourceCatalog::TYPE['ESCJDPGJGHZZS'] => 'escjdpgjghzzs',
        IResourceCatalog::TYPE['SHZZNJXX'] => 'shzznjxx',
        IResourceCatalog::TYPE['GJJLTQYRZXX'] => 'gjjltqyrzxx',
        IResourceCatalog::TYPE['YXZZDWJBGXX'] => 'yxzzdwjbgxx',
        IResourceCatalog::TYPE['CHZZDWXX'] => 'chzzdwxx',
        IResourceCatalog::TYPE['HSZYZGZXX'] => 'hszyzgzxx',
        IResourceCatalog::TYPE['QYGSZXXX'] => 'qygszxxx',
        IResourceCatalog::TYPE['QYDSXZCFXX'] => 'qydsxzcfxx',
        IResourceCatalog::TYPE['AJNSRXX'] => 'ajnsrxx',  
        IResourceCatalog::TYPE['QYJBXX'] => 'qyjbxx',
        IResourceCatalog::TYPE['WXHXPQYBHGLQD'] => 'wxhxpqybhglqd',
        IResourceCatalog::TYPE['EYQFDGRXX'] => 'eyqfdgrxx',       
        IResourceCatalog::TYPE['WFWGTPXX'] => 'wfwgtpxx',
        IResourceCatalog::TYPE['YHYJRJGCFXX'] => 'yhyjrjgcfxx',
        IResourceCatalog::TYPE['LSTDFWBA'] => 'lstdfwba',
        IResourceCatalog::TYPE['EYQFGRXX'] => 'eyqfgrxx',
        IResourceCatalog::TYPE['XZXKQYXX'] => 'xzxkqyxx',
        IResourceCatalog::TYPE['EYQFQYXX'] => 'eyqfqyxx',
        IResourceCatalog::TYPE['SYDWFRDJXX'] => 'sydwfrdjxx',
        IResourceCatalog::TYPE['PXSTYXHDJXX'] => 'pxstyxhdjxx',
        IResourceCatalog::TYPE['DZDAGZZDWGRBZJL'] => 'dzdagzzdwgrbzjl',
        IResourceCatalog::TYPE['JXSZLJDW'] => 'jxszljdw',
        IResourceCatalog::TYPE['DTJXJGRXX'] => 'dtjxjgrxx',
        IResourceCatalog::TYPE['XZCFGSXX'] => 'xzcfgsxx',
        IResourceCatalog::TYPE['XZXKGSXX'] => 'xzxkgsxx',
        IResourceCatalog::TYPE['SXBZXJGXX'] => 'sxbzxjgxx',
        IResourceCatalog::TYPE['SXBZXRMD'] => 'sxbzxrmd',
        IResourceCatalog::TYPE['TEST'] => 'test'
    );
}