<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const TYPE_IDENTIFY = array(
        IUserGroup::ID['NULL'] => 0,
        IUserGroup::ID['SFZHGGWYH'] => 'SFZHGGWYH',
        IUserGroup::ID['GQTPXSW'] => 'GQTPXSW',
        IUserGroup::ID['SWMB'] => 'SWMB',
        IUserGroup::ID['RMYHPXSZXZH'] => 'RMYHPXSZXZH',
        IUserGroup::ID['SQXJ'] => 'SQXJ',
        IUserGroup::ID['SZJRMFY'] => 'SZJRMFY',
        IUserGroup::ID['SLSJ'] => 'SLSJ',
        IUserGroup::ID['SGAJ'] => 'SGAJ',
        IUserGroup::ID['SCZJ'] => 'SCZJ',
        IUserGroup::ID['SGYHXXHWYH'] => 'SGYHXXHWYH',
        IUserGroup::ID['SGYZCJDGLWYH'] => 'SGYZCJDGLWYH',
        IUserGroup::ID['SJYJ'] => 'SJYJ',
        IUserGroup::ID['SSFJ'] => 'SSFJ',
        IUserGroup::ID['SRLZYHSHBZJ'] => 'SRLZYHSHBZJ',
        IUserGroup::ID['SJSJ'] => 'SJSJ',
        IUserGroup::ID['SGHJ'] => 'SGHJ',
        IUserGroup::ID['SRQYXGS'] => 'SRQYXGS',
        IUserGroup::ID['SSLJ'] => 'SSLJ',
        IUserGroup::ID['SGDGS'] => 'SGDGS',
        IUserGroup::ID['SLYJ'] => 'SLYJ',
        IUserGroup::ID['SJTYSJ'] => 'SJTYSJ',
        IUserGroup::ID['SLYFZWYH'] => 'SLYFZWYH',
        IUserGroup::ID['SFDCGLJ'] => 'SFDCGLJ',
        IUserGroup::ID['SHJBHJ'] => 'SHJBHJ',
        IUserGroup::ID['SSWJ'] => 'SSWJ',
        IUserGroup::ID['SMZJ'] => 'SMZJ',
        IUserGroup::ID['SNYJ'] => 'SNYJ',
        IUserGroup::ID['SWHGDXWCBS'] => 'SWHGDXWCBS',
        IUserGroup::ID['SGTZYJ'] => 'SGTZYJ',
        IUserGroup::ID['SWSHJHSYWYH'] => 'SWSHJHSYWYH',
        IUserGroup::ID['SGJSWJ'] => 'SGJSWJ',
        IUserGroup::ID['SDFSWJ'] => 'SDFSWJ',
        IUserGroup::ID['STJJ'] => 'STJJ',
        IUserGroup::ID['SSCHZLJGGLJ'] => 'SSCHZLJGGLJ',
        IUserGroup::ID['SAQSCJDGLJ'] => 'SAQSCJDGLJ',
        IUserGroup::ID['ZGYDPXFGS'] => 'ZGYDPXFGS',
        IUserGroup::ID['PXHCZPXBZ'] => 'PXHCZPXBZ',
        IUserGroup::ID['SYJFJ'] => 'SYJFJ',
        IUserGroup::ID['SGGZWGLJ'] => 'SGGZWGLJ',
        IUserGroup::ID['ZGDXPXFGS'] => 'ZGDXPXFGS',
        IUserGroup::ID['SCSGLXZZFJ'] => 'SCSGLXZZFJ',
        IUserGroup::ID['ZGLTPXFGS'] => 'ZGLTPXFGS',
        IUserGroup::ID['SJGBZWYHBGS'] => 'SJGBZWYHBGS',
        IUserGroup::ID['STYJ'] => 'STYJ',
        IUserGroup::ID['SDAJ'] => 'SDAJ',
        IUserGroup::ID['SKXJSJ'] => 'SKXJSJ'
    );
}